name: cd

trigger: none

resources:
  pipelines:
  - pipeline: dependent-cd-pipeline
    source: ci
    project: email
    branch: main
    trigger:
      branches:
        include:
        - main 

pool:
  vmImage: ubuntu-latest

variables:
  appName: 'morsley-uk-email-api'
  artifactName: 'drop'
  azureSubscription: 'morsley-uk-email'  
  packagePath: 'Morsley.UK.Email.API.zip'

steps:
# Download artifacts from CI pipeline...
- task: DownloadPipelineArtifact@2
  displayName: "--> Download CI Pipeline Artifacts <--"
  inputs:
    buildType: 'specific'
    project: 'email'
    definition: 'ci'
    buildVersionToDownload: 'latest'
    artifactName: 'drop'
    targetPath: '$(Pipeline.Workspace)/artifacts'

# Show downloaded artifacts...
- task: CmdLine@2
  displayName: "--> Show Downloaded Artifacts <--"
  inputs:
    script: |
      echo "Contents of artifacts directory:"
      ls -la $(Pipeline.Workspace)/artifacts
      echo "Contents of publish directory:"
      ls -la $(Pipeline.Workspace)/artifacts/publish

# Verify deployment package exists...
- task: CmdLine@2
  displayName: "--> Verify Deployment Package From CI Pipeline <--"
  inputs:
    script: |
      if [ -f "$(Pipeline.Workspace)/artifacts/publish/Morsley.UK.Email.API.zip" ]; then
        echo "OK: Deployment package found: Morsley.UK.Email.API.zip"
        echo "Package size: $(stat -f%z "$(Pipeline.Workspace)/artifacts/publish/Morsley.UK.Email.API.zip" 2>/dev/null || stat -c%s "$(Pipeline.Workspace)/artifacts/publish/Morsley.UK.Email.API.zip") bytes"
        echo "Package contents:"
        unzip -l "$(Pipeline.Workspace)/artifacts/publish/Morsley.UK.Email.API.zip" | head -20
      else
        echo "ERROR: Deployment package not found!"
        echo "Available files in artifacts directory:"
        find $(Pipeline.Workspace)/artifacts -type f -name "*.zip"
        exit 1
      fi

# Deploy our email API to production...  
- task: AzureWebApp@1
  displayName: '--> Deploy to Production <--'
  inputs: 
    azureSubscription: '$(azureSubscription)'
    appName: '$(appName)'
    appType: 'webApp'
    package: '$(Pipeline.Workspace)/artifacts/publish/Morsley.UK.Email.API.zip'
    deploymentMethod: 'auto'

# Run system tests against deployed API (smoke tests)...
#- task: DotNetCoreCLI@2
#  displayName: "--> Run System Tests Against Production <--"
#  inputs:
#    command: test
#    projects: 'tests/Morsley.UK.Email.API.SystemTests/Morsley.UK.Email.API.SystemTests.csproj'
#    arguments: '--configuration $(BuildConfiguration)'
#    publishTestResults: true
#  env:
#    API_BASE_URL: 'https://$(appName).azurewebsites.net'